<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Posts' => 'Посты',
    'Create Post' => 'Создать пост',
    'Creating Post' => 'Создание поста',
    'Updating Post' => 'Обновление поста',
    'Active' => 'Активный',
    'Deactive' => 'Отключён',
    'Post ID' => 'Идентификатор поста',
    'Title' => 'Заголовок',
    'Subtitle' => 'Под зоголовок',
    'Description' => 'Описание',
    'Content' => 'Контент',
    'Slug' => 'Слаг',
    'Sort' => 'Сортировка',
    'Date update' => 'Дата побновление',
    'Date create' => 'Дата добавление',
    'Date publish' => 'Дата публикации',
    'Status' => 'Статус',
    'Lang hash' => 'Хеш языка',
    'Lang' => 'Языка',
    'User' => 'Пользователь',
    'Search' => 'Поиск',
    'Reset' => 'Сброс',
    'Updating' => 'Обновление',
    'Update' => 'Обновить',
    'Delete' => 'Удалить',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить?',
];
